SiteWebJO2/Controllers/MockPaymentController.cs
using Microsoft.AspNetCore.Mvc;
using SiteWebJO2.Models;
using System.Numerics;


namespace SiteWebJO2.Controllers
{
    [AutoValidateAntiforgeryToken]
    public class MockPaymentController : Controller
    {

        /// <summary>
        /// entry to Payment API
        /// </summary>
        /// <param name="orderId">order to treat</param>
        /// <param name="orderAmount">amount of order</param>
        /// <param name="clientSiteKey">client key to recognize client id</param>
        /// <returns>view MockPayment/PaymentProcess, to display order informations and ask for payment </returns>
        public IActionResult PaymentProcess(int orderId, decimal orderAmount, string clientSiteKey)
        {

            //identify clientSite
            string clientName = "";
            if(clientSiteKey == Environment.GetEnvironmentVariable("ApiPaymentKey"))
            {
                clientName = "Jo2024Tickets";
            }

            // create new Transaction
            string transactionId = Guid.NewGuid().ToString();
            string status = "Created";
            Transaction transaction = new Transaction(transactionId, orderId, orderAmount, clientName, status);
            
            return View(transaction);
        }


        /// <summary>
        /// user pay successful, call client web site to inform
        /// </summary>
        /// <param name="transaction">transation treated</param>
        /// <returns>redirect to client app, with status 'Success'</returns>
        [HttpPost]
        public IActionResult PaymentOk(Transaction transaction)
        {
            transaction.Status = "Success";
            return RedirectToAction("OrderTreatment", "ShoppingCarts",  new { orderId = transaction.OrderId, orderAmount = transaction.OrderAmount, transactionId = transaction.TransactionId, status = transaction.Status});
        }

        /// <summary>
        /// user pay abort, call client web site to inform
        /// </summary>
        /// <param name="transaction">transation treated</param>
        /// <returns>redirect to client app, with status 'Abort'</returns>
        [HttpPost]
        public IActionResult PaymentAbort(Transaction transaction)
        {
            transaction.Status = "Abort";
            return RedirectToAction("OrderTreatment", "ShoppingCarts", new { orderId = transaction.OrderId, orderAmount = transaction.OrderAmount, transactionId = transaction.TransactionId, status = transaction.Status });
        }
    }


    /// <summary>
    /// class to define object manipulated by MockPayment
    /// </summary>
    public class Transaction
    {
        public string TransactionId { get; set; }
        public int OrderId { get; set; } 
        public decimal OrderAmount { get; set; } 
        public string ClientName { get; set; } 
        public string Status { get; set; }

        public Transaction()
        {
            // Parameterless constructor
        }

        public Transaction (string transactionId, int orderId, decimal orderAmount, string clientName, string status)
        {
            TransactionId =transactionId;
            OrderId= orderId;
            OrderAmount= orderAmount;
            ClientName = clientName;
            Status= status;
        }

    }
}

SiteWebJO2/Views/MockPayment/PaymentProcess.cshtml
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Antiforgery
@* https://learn.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-8.0 *@

@using SiteWebJO2.Controllers
@model SiteWebJO2.Controllers.Transaction

@{
    ViewData["Title"] = "Payment";
    Layout = null;
    var requestToken = Antiforgery.GetAndStoreTokens(Context).RequestToken;
}


<input id="RequestVerificationToken" type="hidden" value="@requestToken" />

<h1>Welcome to Stripe Payment</h1>

<strong>Note: This is a fake site for educational purpose only</strong>

<h3>Your payment from the site : @Model.ClientName</h3>

<h3>Order Id: #@Model.OrderId</h3>

<h3>Amount to pay: @Model.OrderAmount €</h3>

@using (Html.BeginForm("PaymentOk", "MockPayment", FormMethod.Post))
{
    <input type="hidden" asp-for="TransactionId" value=@Model.TransactionId />
    <input type="hidden" asp-for="OrderId" value=@Model.OrderId />
    <input type="hidden" asp-for="OrderAmount" value=@Model.OrderAmount />
    <input type="hidden" asp-for="ClientName" value=@Model.ClientName />
    <input type="hidden" asp-for="Status" value=@Model.Status />
    <button type="submit">Accept payment</button>

}


@using (Html.BeginForm("PaymentAbort", "MockPayment", FormMethod.Post))
{
    <input type="hidden" asp-for="TransactionId" value=@Model.TransactionId />
    <input type="hidden" asp-for="OrderId" value=@Model.OrderId />
    <input type="hidden" asp-for="OrderAmount" value=@Model.OrderAmount />
    <input type="hidden" asp-for="ClientName" value=@Model.ClientName />
    <input type="hidden" asp-for="Status" value=@Model.Status />
    <button type="submit">Refuse payment</button>
}