SiteWebJO2/Controllers/JoSessionsController.cs
using Microsoft.AspNetCore.Mvc;
using SiteWebJO2.Models;
using SiteWebJO2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;

namespace SiteWebJO2.Controllers
{
    public class JoSessionsController : Controller
    {
        private readonly ApplicationDbContext _applicationDbContext;

        //constructor, with dependency injection of dbContext
        public JoSessionsController(ApplicationDbContext applicationDbContext)
        {
            _applicationDbContext = applicationDbContext;
        }


        /// <summary>
        /// display list of sessions
        /// </summary>
        /// <param name="sortOrder">user can choose the sort order</param>
        /// <param name="currentFilter">filter already used to filter the list</param>
        /// <param name="searchString">the string the list is filtered on</param>
        /// <param name="pageNumber">the number of the page displayed</param>
        /// <returns>view according to filter and sort parameters</returns>
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;

            if (String.IsNullOrEmpty(sortOrder)){ sortOrder = "date_asc"; }
            ViewData["NameSortParm"] = sortOrder == "name_desc" ? "name_asc" : "name_desc";
            ViewData["PlaceSortParm"] = sortOrder == "place_desc" ? "place_asc" : "place_desc";
            ViewData["DateSortParm"] = sortOrder == "date_asc" ? "date_desc" : "date_asc";
            ViewData["CurrentFilter"] = searchString;

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            // get JoSessions data
            var js = from s in _applicationDbContext.JoSessions
                     select s;
            js = GetAvailableJoSessions(js);

            // filtering data
            if (!String.IsNullOrEmpty(searchString))
            {
                js = js.Where(s => s.JoSessionName.Contains(searchString)
                                       || s.JoSessionPlace.Contains(searchString)
                                        );
            }

            // sorting data
            switch (sortOrder)
            {
                case "name_desc":
                    js = js.OrderByDescending(s => s.JoSessionName);
                    break;
                case "name_asc":
                    js = js.OrderBy(s => s.JoSessionName);
                    break;
                case "place_desc":
                    js = js.OrderByDescending(s => s.JoSessionPlace);
                    break;
                case "place_asc":
                    js = js.OrderBy(s => s.JoSessionPlace);
                    break;
                case "":
                default:
                    js = js.OrderBy(s => s.JoSessionDate);
                    break;
                case "date_desc":
                    js = js.OrderByDescending(s => s.JoSessionDate);
                    break;
            }
            int pageSize = 10;

            return View(await PaginatedList<JoSession>.CreateAsync(js.AsNoTracking(), pageNumber ?? 1, pageSize));
        }


        /// <summary>
        /// display offers concerning JoSession selected
        /// </summary>
        /// <param name="joSessionId">id of session chosen</param>
        /// <returns>view</returns>
        [Route("JoSessions/Details/{joSessionId}")]
        public async Task<IActionResult> Details(int? joSessionId)
        {
            if (joSessionId == null || _applicationDbContext.JoSessions == null)
            {
                return NotFound();
            }

            var joSession = await _applicationDbContext.JoSessions.FirstOrDefaultAsync(s => s.JoSessionId == joSessionId);
            if (joSession == null) 
            { 
                return NotFound();
            }
            //save selected joSession data in Html session
            HttpContext.Session.SetInt32("joSessionId", joSession.JoSessionId);
            HttpContext.Session.SetString("joSessionName", joSession.JoSessionName);
            HttpContext.Session.SetString("joSessionPlace", joSession.JoSessionPlace);
            HttpContext.Session.SetString("joSessionDate", joSession.JoSessionDate.ToString());
            HttpContext.Session.SetString("joSessionDescription", joSession.JoSessionDescription);
            HttpContext.Session.SetString("joSessionImage", joSession.JoSessionImage);
            HttpContext.Session.SetString("joSessionPrice", joSession.JoSessionPrice.ToString());

            // get JoTicketPacks data
            var js = from s in _applicationDbContext.JoTicketPacks
                     select s;
            js = GetOnUseJoTicketPacks(js);

            return View(js);
        }



        /// <summary>
        /// get available JoSessions
        /// </summary>
        /// <param name="joSessionsList">all existing sessions</param>
        /// <returns>list of available sessions</returns>
        public static IQueryable<JoSession> GetAvailableJoSessions(IQueryable<JoSession> joSessionsList)
        {
            return joSessionsList.Where(s => s.JoSessionNbTotalBooked < s.JoSessionNbTotalAttendees);
        }


        /// <summary>
        /// get on use JoTicketPack
        /// </summary>
        /// <param name="joTicketPacksList">all existing packs</param>
        /// <returns>list of packs in use</returns>
        public static IQueryable<JoTicketPack> GetOnUseJoTicketPacks(IQueryable<JoTicketPack> joTicketPacksList)
        {
            return joTicketPacksList.Where(p => p.JoTicketPackStatus);
        }


        /// <summary>
        /// calculate price of joTicketPack
        /// </summary>
        /// <param name="joSessionPrice">price of 1 attendee for the session</param>
        /// <param name="nbAttendees">number of attendees</param>
        /// <param name="reductionRate">reduction to apply to the price</param>
        /// <returns>price for the session and pack chosen</returns>
        public static decimal GetJoTicketPackPrice (decimal joSessionPrice, int nbAttendees, decimal reductionRate)
        {
            return Math.Round(Convert.ToDecimal(joSessionPrice) * (1 - reductionRate) * nbAttendees, 2);
        }


        /// <summary>
        /// add data in database, call it manually with .../JoSessions/AddData
        /// create JoSessions, JoTicketsPacks
        /// </summary>
        /// <returns></returns>
        [Authorize(Roles = "ADMIN")]
        public async Task<IActionResult> AddData()
        {
            /*
             * Add JoSessions
             * JoSessionId: auto increment
             */
            List<JoSession> JoSessionsList = new List<JoSession>
                {
                new JoSession {JoSessionName = "Equestrian Dressage - Mixed", JoSessionDate = new DateTime(2024, 8, 1, 11, 0, 0), JoSessionPlace = "Versailles, Château de Versailles", JoSessionNbTotalAttendees= 10000, JoSessionNbTotalBooked= 5000, JoSessionDescription="EQD01 Dressage grand prix team and individual qualifier", JoSessionImage=@"~/images/Equestrian.jpg", JoSessionPrice=50 },
                new JoSession {JoSessionName = "Artistic swimming - Female", JoSessionDate = new DateTime(2024, 8, 10, 19, 30, 0), JoSessionPlace = "St Denis, Aquatics centre", JoSessionNbTotalAttendees= 8000, JoSessionNbTotalBooked= 8000, JoSessionDescription="SWA05 Duet free routine", JoSessionImage= @"~/images/Artistic Swimming.jpg", JoSessionPrice=80 },
                new JoSession {JoSessionName = "Rowing - Mixed", JoSessionDate = new DateTime(2024, 7, 29, 9, 30, 0), JoSessionPlace = "Vaires-sur-Marne, Nautical St. - Flatwater", JoSessionNbTotalAttendees= 15000, JoSessionNbTotalBooked= 6000, JoSessionDescription="ROW01 M/W - Heats\r\n\r\nScheduled events (subject to change):\r\nMen's Single Sculls Heats\r\nWomen's Single Sculls Heats\r\nMen's Double Sculls Heats\r\nWomen's Double Sculls Heats\r\nMen's Quadruple Sculls Heats\r\nWomen's Quadruple Sculls Heats", JoSessionImage = @"~/images/Rowing.jpg", JoSessionPrice=30 },
                new JoSession {JoSessionName = "Volleyball - Male", JoSessionDate = new DateTime(2024, 7, 31, 9, 0, 0), JoSessionPlace = "Paris, South Paris Arena 1", JoSessionNbTotalAttendees= 5000, JoSessionNbTotalBooked= 4000, JoSessionDescription="VVO16 M - Preliminary round", JoSessionImage = @"~/images/Volleyball.jpg", JoSessionPrice=90 },
                new JoSession {JoSessionName = "Cycling Moutain Bike - Female", JoSessionDate = new DateTime(2024, 7, 28, 14, 0, 0), JoSessionPlace = "St-Quentin-En-Yvelines, Elancourt Hill", JoSessionNbTotalAttendees= 20000, JoSessionNbTotalBooked= 12000, JoSessionDescription="", JoSessionImage = @"~/images/Cycling Moutain Bike.jpg", JoSessionPrice=70 },
                new JoSession {JoSessionName = "Football - Male", JoSessionDate = new DateTime(2024, 7, 24, 15, 0, 0), JoSessionPlace = "Paris, Parc des Princes", JoSessionNbTotalAttendees= 10000, JoSessionNbTotalBooked= 5000, JoSessionDescription="FBL01 M - AFC2 vs Spain group stage", JoSessionImage=@"~/images/Football.jpg", JoSessionPrice=50 },
                new JoSession {JoSessionName = "Football - Female", JoSessionDate = new DateTime(2024, 7, 25, 17, 00, 0), JoSessionPlace = "Nantes, La Beaujoire Stadium", JoSessionNbTotalAttendees= 8000, JoSessionNbTotalBooked= 8000, JoSessionDescription="FBL03 M - Egypt vs Dominican Republic group stage", JoSessionImage= @"~/images/Football.jpg", JoSessionPrice=30 },

SiteWebJO2/Views/ShoppingCarts/Checkout.cshtml
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Antiforgery
@* https://learn.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-8.0 *@


@{
    ViewData["Title"] = "Order checkout";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var requestToken = Antiforgery.GetAndStoreTokens(Context).RequestToken;
}

<input id="RequestVerificationToken" type="hidden" value="@requestToken" />

<div class="d-inline-flex mb-3 container justify-content-center">
    <h1 class="fontBlue mansalva-regular me-3">@ViewData["Title"]</h1>
</div>

<div class="d-inline-flex container row">
    <div class="col col-8" id="orderSummary">
        <table class="table" id="checkoutTable">
            <thead class="text-center text-light bgBlue">
                <tr>
                    <th scope="col" class="col-2"></th>
                    <th scope="col" class="col-8">Summary</th>
                    <th scope="col" class="col-2"></th>
                </tr>
            </thead>
            <tbody id="checkoutTableBody">
                @* display the tickets selected by user, written by javascript *@
            </tbody>
        </table>
        @* display the order subtotal *@
        <div class="row d-inline-flex container">
            <div scope="col" class="col-6 text-start">
                <a asp-area="" asp-controller="ShoppingCarts" asp-action="Index">Change order</a>
            </div>
            <div scope="col" class="col-6 text-end d-inline">
                <h5 id="subtotal" class="text-end d-inline">
                </h5>
            </div>
        </div>
    </div>

    <div class="col col-4" id="orderConditions">
        @* display the order conditions *@
        <div class="joCard">
            <h5>Conditions</h5>
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
                <label class="form-check-label" for="flexCheckDefault">
                    I have read and accept the <a href="~/Home/TicketingTerms">Ticketing Terms and Conditions</a>. I have also read the <a href="~/Home/Privacy">Privacy Policy</a>.
                </label>
            </div>
        </div>

        @* display the name on tickets *@
        <div class="joCard">
            <h5>Name on ticket</h5>
            <p id="namesUser" class="text-capitalize"</p>
        </div>

        <div class=" text-end">
            <a id="GoToPayment" class="btn btn-lg mb-3 mt-3 letsgoBtn" onclick="checkConditionsTicked();">Go to payment</a>
            <p>After this step, you will be redirected to the secure payment page to choose and enter your payment details</p>
        </div>

    </div>


</div>



<script>
    window.onload = function () {
        displayCheckoutPage()
    };


    // check that conditions are accepted by user before continue to payment
    function checkConditionsTicked() {
        if (!document.getElementById("flexCheckDefault").checked) {
            var myModalElement = customModal("Can not continue", "You must check conditions and policy rules before go on to payment");
            myModalElement.show();
        }
        // check that shopping cart is not empty (possible to append when go on previous pages)
        else if (getCookie("jo2024Cart") == []) {
            var myModalElement = customModal("Can not continue", "Your shopping cart is empty");
            myModalElement.show();
        }
        else {
            window.location.href = '/ShoppingCarts/Payment';
        }

    }
</script>

SiteWebJO2/Views/ShoppingCarts/Index.cshtml
@model SiteWebJO2.Models.ShoppingCartTicket
@inject Microsoft.AspNetCore.Antiforgery.IAntiforgery Antiforgery
@* https://learn.microsoft.com/en-us/aspnet/core/security/anti-request-forgery?view=aspnetcore-8.0 *@

@{
    ViewData["Title"] = "Your shopping cart";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var requestToken = Antiforgery.GetAndStoreTokens(Context).RequestToken;
}

<input id="RequestVerificationToken" type="hidden" value="@requestToken" />

<div class="d-inline-flex mb-3 container justify-content-center">
    <h1 class="fontBlue mansalva-regular me-3">@ViewData["Title"]</h1>
</div>

<div id="shoppingCartTablePosition">
    <table class="table" id="shoppingCartTable">
        <thead class="text-center text-light bgBlue">
            <tr>
                <th scope="col" class="col-2"></th>
                <th scope="col" class="col-4" style="color: white">
                    Sport Session
                </th>
                <th scope="col" class="col-2" style="color: white">
                    Quantity
                </th>
                <th scope="col" class="col-2" style="color: white">
                    Price each
                </th>
                <th scope="col" class="col-2" style="color: white">
                    Total price
                </th>
            </tr>
        </thead>
        <tbody id="shoppingCartTableBody">
            @* display the tickets selected by user, written by javascript *@
        </tbody>
    </table>
</div>
<div class="row d-inline-flex container">
    <div scope="col" class="col-6 text-start">
        <a asp-area="" asp-controller="JoSessions" asp-action="Index">Back to List</a>
    </div>
    <div scope="col" class="col-6 text-end d-inline">
        <h5 id="subtotal">
            @* display the shopping cart subtotal, written by javascript *@
        </h5>
        <a id="ContinueToPayment" class="btn btn-lg mb-3 mt-3 letsgoBtn" asp-area="" asp-controller="ShoppingCarts" asp-action="Checkout">Continue to payment</a>
    </div>
</div>


<script>
    window.onload = function() {
        displayShoppingCart()
    };
</script>
    

SiteWebJO2/Views/ShoppingCarts/OrderTreatment.cshtml
@model Order
@{
    ViewData["Title"] = "Order on treatment...";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



@if(@Model!=null)
{
    <div class="d-inline-flex mb-3 mt-3 container justify-content-center">
        <h1 class="fontBlue mansalva-regular me-3">@ViewData["Title"]</h1>
    </div>
    
    <div class="mb-5 mt-3">
        <h1 class="text-center">Payment success</h1>
        <h5 class="text-center">Transaction id #@Model.TransactionId</h5>
    </div>
    <div class="mb-3">
        <p>You will receive a mail with your tickets and invoice <strong>#@Model.OrderId</strong> soon</p>
        <p>Please present yourself to the event 2 hours before starting time with your(s) ticket(s)</p>
        <p>QR code must be visible, and you must present an official ID card to justify your identity.</p>
    </div>
    <div scope="col" class="col-6 text-start">
        <a asp-area="" asp-controller="Home" asp-action="Index">Back to Home</a>
    </div>
}
else
{
    <div class="mb-5 mt-5">
        <h1 class="text-center">Payment abort</h1>
    </div>
    <div>
        <br />
        <div scope="col" class="col-6 text-start">
            <a asp-area="" asp-controller="ShoppingCarts" asp-action="Index">Back to shopping cart</a>
        </div>
    </div>
    <br />

}